from app.supabase import supabase

def seed_large_shops():
    extra_shops = [
        # --- CNC Milling Shops (9 shops) ---
        {
            "name": "Pasadena Precision CNC",
            "description": "High-tolerance aerospace milling, medical tooling, and custom aluminum enclosures.",
            "address": "1200 E Green St, Pasadena, CA",
            "capabilities": ["CNC Milling"],
            "materials": ["Aluminum", "Steel", "Titanium", "Brass"],
            "hourly_rate": 115.0,
            "min_order": 250.0,
            "turnaround_days": 5,
            "rating": 4.8,
            "lat": 34.1430,
            "lng": -118.1250,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Silicon Valley CNC Machining",
            "description": "Prototype and low-volume production CNC milling. Rapid response and high-precision finishes.",
            "address": "450 Tech Way, San Jose, CA",
            "capabilities": ["CNC Milling"],
            "materials": ["Aluminum", "Copper", "Carbon Fiber", "ABS"],
            "hourly_rate": 130.0,
            "min_order": 500.0,
            "turnaround_days": 3,
            "rating": 4.9,
            "lat": 37.3382,
            "lng": -121.8863,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Lone Star Tool & Die",
            "description": "Heavy-duty CNC milling for oil and gas components. Deep bores and large envelope CNC.",
            "address": "1900 Industry Road, Houston, TX",
            "capabilities": ["CNC Milling"],
            "materials": ["Steel", "Stainless Steel", "Titanium"],
            "hourly_rate": 105.0,
            "min_order": 1000.0,
            "turnaround_days": 14,
            "rating": 4.6,
            "lat": 29.7604,
            "lng": -95.3698,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Boulder Micro-Milling Inc.",
            "description": "Micro-precision milling for research labs, electronics housing, and optical mounts.",
            "address": "888 Canyon Blvd, Boulder, CO",
            "capabilities": ["CNC Milling"],
            "materials": ["Aluminum", "Brass", "Titanium", "Polycarbonate"],
            "hourly_rate": 145.0,
            "min_order": 600.0,
            "turnaround_days": 8,
            "rating": 4.7,
            "lat": 40.0150,
            "lng": -105.2705,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Seattle Aero-Substrates",
            "description": "High-fidelity CNC milling, 5-axis aerospace composites and titanium specialized structures.",
            "address": "777 Flightline Rd, Renton, WA",
            "capabilities": ["CNC Milling"],
            "materials": ["Titanium", "Aluminum", "Carbon Fiber"],
            "hourly_rate": 160.0,
            "min_order": 1500.0,
            "turnaround_days": 10,
            "rating": 4.9,
            "lat": 47.4829,
            "lng": -122.2171,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Midwest Engineering Hub",
            "description": "Comprehensive CNC milling, custom fixture production, and bulk raw material machining.",
            "address": "3340 Hub Lane, Des Moines, IA",
            "capabilities": ["CNC Milling"],
            "materials": ["Steel", "Aluminum", "Brass", "Copper"],
            "hourly_rate": 90.0,
            "min_order": 200.0,
            "turnaround_days": 7,
            "rating": 4.4,
            "lat": 41.5868,
            "lng": -93.6250,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Great Lakes CNC Center",
            "description": "Automotive-grade CNC milling. Specialized in mass-production engine parts and complex manifolds.",
            "address": "500 Assembly Way, Detroit, MI",
            "capabilities": ["CNC Milling"],
            "materials": ["Steel", "Stainless Steel", "Aluminum"],
            "hourly_rate": 98.0,
            "min_order": 1200.0,
            "turnaround_days": 12,
            "rating": 4.7,
            "lat": 42.3314,
            "lng": -83.0458,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Empire Precision Milling",
            "description": "Premium industrial grade CNC milling. Clean-room machining and vacuum packaging available.",
            "address": "99 Industrial Pkwy, Rochester, NY",
            "capabilities": ["CNC Milling"],
            "materials": ["Stainless Steel", "Titanium", "Nylon"],
            "hourly_rate": 135.0,
            "min_order": 800.0,
            "turnaround_days": 6,
            "rating": 4.8,
            "lat": 43.1566,
            "lng": -77.6088,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Florida Coastline Engineering",
            "description": "Marine-grade CNC milling, stainless steel hardware, and anodized aluminum parts.",
            "address": "220 Yacht Club Rd, Fort Lauderdale, FL",
            "capabilities": ["CNC Milling"],
            "materials": ["Stainless Steel", "Aluminum", "Brass"],
            "hourly_rate": 110.0,
            "min_order": 300.0,
            "turnaround_days": 5,
            "rating": 4.5,
            "lat": 26.1224,
            "lng": -80.1373,
            "verified": False,
            "is_active": True
        },

        # --- 3D Printing (FDM) (7 shops) ---
        {
            "name": "Austin Rapid FDM",
            "description": "Lightning-fast FDM 3D printing for rapid enclosures, architectural mockups, and early stage test fits.",
            "address": "902 Tech Trail, Austin, TX",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["PLA", "ABS", "PETG", "Carbon Fiber"],
            "hourly_rate": 35.0,
            "min_order": 30.0,
            "turnaround_days": 1,
            "rating": 4.8,
            "lat": 30.2672,
            "lng": -97.7431,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Denver Bio-Plastics Fab",
            "description": "Eco-friendly FDM printing specializing in recycled and biodegradable PLA filaments.",
            "address": "1420 Eco Way, Denver, CO",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["PLA", "PETG"],
            "hourly_rate": 30.0,
            "min_order": 20.0,
            "turnaround_days": 2,
            "rating": 4.6,
            "lat": 39.7392,
            "lng": -104.9903,
            "verified": True,
            "is_active": True
        },
        {
            "name": "NYC Structural Filament Co.",
            "description": "High-strength FDM 3D printing utilizing carbon-fiber reinforced plastics and high-temp polycarbonate.",
            "address": "77 Grand St, Brooklyn, NY",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["Carbon Fiber", "ABS", "PETG"],
            "hourly_rate": 50.0,
            "min_order": 100.0,
            "turnaround_days": 3,
            "rating": 4.7,
            "lat": 40.7128,
            "lng": -74.0060,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Portland Fusion Tech",
            "description": "Large-format FDM printing. Print volume up to 1 cubic meter for full-size visual mockups.",
            "address": "606 Burnside St, Portland, OR",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["PLA", "PETG", "ABS"],
            "hourly_rate": 45.0,
            "min_order": 150.0,
            "turnaround_days": 4,
            "rating": 4.5,
            "lat": 45.5152,
            "lng": -122.6784,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Chicago Rapid Filament",
            "description": "Industrial grade FDM printing. Dual-extrusion support, soluble support structures, and flexible TPU materials.",
            "address": "120 N Michigan Ave, Chicago, IL",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["ABS", "PLA", "PETG"],
            "hourly_rate": 38.0,
            "min_order": 40.0,
            "turnaround_days": 2,
            "rating": 4.6,
            "lat": 41.8781,
            "lng": -87.6298,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Salt Lake High-Volume FDM",
            "description": "Production-scale FDM farm. Print up to 500 parts simultaneously for ultra-rapid batch scaling.",
            "address": "320 Skyline Dr, Salt Lake City, UT",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["PLA", "PETG", "ABS"],
            "hourly_rate": 32.0,
            "min_order": 250.0,
            "turnaround_days": 3,
            "rating": 4.7,
            "lat": 40.7608,
            "lng": -111.8910,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Dallas Precision Extrusion",
            "description": "Precision engineering-grade FDM printing for functional automotive parts and custom tooling.",
            "address": "8100 STEMMONS FREEWAY, Dallas, TX",
            "capabilities": ["3D Printing (FDM)"],
            "materials": ["ABS", "Carbon Fiber", "PETG"],
            "hourly_rate": 48.0,
            "min_order": 80.0,
            "turnaround_days": 2,
            "rating": 4.8,
            "lat": 32.7767,
            "lng": -96.7970,
            "verified": True,
            "is_active": True
        },

        # --- 3D Printing (SLA) (6 shops) ---
        {
            "name": "Boston High-Res SLA",
            "description": "Precision SLA printing. Perfect for injection molding masters, microfluidics, and highly detailed visual models.",
            "address": "100 Innovation Way, Boston, MA",
            "capabilities": ["3D Printing (SLA)"],
            "materials": ["Resin"],
            "hourly_rate": 70.0,
            "min_order": 120.0,
            "turnaround_days": 3,
            "rating": 4.9,
            "lat": 42.3601,
            "lng": -71.0589,
            "verified": True,
            "is_active": True
        },
        {
            "name": "San Diego Bio-Resins",
            "description": "Sterile, biocompatible, and high-temp resins for medical devices and surgical guides.",
            "address": "450 Torrey Pines Rd, La Jolla, CA",
            "capabilities": ["3D Printing (SLA)"],
            "materials": ["Resin"],
            "hourly_rate": 95.0,
            "min_order": 300.0,
            "turnaround_days": 4,
            "rating": 4.8,
            "lat": 32.8473,
            "lng": -117.2742,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Phoenix Micro-Detail SLA",
            "description": "Ultra-precise SLA printing. 25-micron layer heights for fine jewelry casting and miniature dental tooling.",
            "address": "1800 Desert Cove, Phoenix, AZ",
            "capabilities": ["3D Printing (SLA)"],
            "materials": ["Resin"],
            "hourly_rate": 60.0,
            "min_order": 90.0,
            "turnaround_days": 2,
            "rating": 4.5,
            "lat": 33.4484,
            "lng": -112.0740,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Atlanta Creative Resins",
            "description": "Specialized resin prints including flexible, clear, and tough engineering-grade SLA resins.",
            "address": "90 Peachtree St, Atlanta, GA",
            "capabilities": ["3D Printing (SLA)"],
            "materials": ["Resin"],
            "hourly_rate": 68.0,
            "min_order": 100.0,
            "turnaround_days": 3,
            "rating": 4.6,
            "lat": 33.7490,
            "lng": -84.3880,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Palo Alto Prototype Lab",
            "description": "High-fidelity quick turn SLA printing for Silicon Valley startups. 24-hour turnaround available.",
            "address": "3000 El Camino Real, Palo Alto, CA",
            "capabilities": ["3D Printing (SLA)"],
            "materials": ["Resin"],
            "hourly_rate": 80.0,
            "min_order": 150.0,
            "turnaround_days": 1,
            "rating": 4.9,
            "lat": 37.4419,
            "lng": -122.1430,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Pittsburgh Engineering Resins",
            "description": "SLA printing with high strength, flame retardant, and high-deflection-temperature resins.",
            "address": "4400 Forbes Ave, Pittsburgh, PA",
            "capabilities": ["3D Printing (SLA)"],
            "materials": ["Resin"],
            "hourly_rate": 75.0,
            "min_order": 200.0,
            "turnaround_days": 3,
            "rating": 4.7,
            "lat": 40.4406,
            "lng": -79.9959,
            "verified": False,
            "is_active": True
        },

        # --- Laser Cutting (6 shops) ---
        {
            "name": "Austin Laser Express",
            "description": "Premium industrial grade high-power CO2 laser cutting for woods, acrylics, and fabrics.",
            "address": "402 E 6th St, Austin, TX",
            "capabilities": ["Laser Cutting"],
            "materials": ["Acrylic", "Wood", "Leather"],
            "hourly_rate": 45.0,
            "min_order": 50.0,
            "turnaround_days": 2,
            "rating": 4.7,
            "lat": 30.2672,
            "lng": -97.7431,
            "verified": True,
            "is_active": True
        },
        {
            "name": "LA Sheet & Acrylic Cutters",
            "description": "Professional laser cutting specializing in thick industrial plastics and precision structural panels.",
            "address": "1100 S Grand Ave, Los Angeles, CA",
            "capabilities": ["Laser Cutting"],
            "materials": ["Acrylic", "Polycarbonate", "Wood"],
            "hourly_rate": 55.0,
            "min_order": 80.0,
            "turnaround_days": 3,
            "rating": 4.6,
            "lat": 34.0522,
            "lng": -118.2437,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Oakland Industrial Laser",
            "description": "High-tolerance laser cutting for thin steel, structural wood panels, and architectural models.",
            "address": "2200 Broadway, Oakland, CA",
            "capabilities": ["Laser Cutting"],
            "materials": ["Steel", "Wood", "Acrylic"],
            "hourly_rate": 60.0,
            "min_order": 100.0,
            "turnaround_days": 2,
            "rating": 4.7,
            "lat": 37.8044,
            "lng": -122.2712,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Tampa Bay Custom Cuts",
            "description": "Fine engraving, vector graphics, sign manufacturing, and custom wood panels.",
            "address": "802 Ybor St, Tampa, FL",
            "capabilities": ["Laser Cutting"],
            "materials": ["Wood", "Acrylic", "Leather"],
            "hourly_rate": 40.0,
            "min_order": 40.0,
            "turnaround_days": 1,
            "rating": 4.8,
            "lat": 27.9506,
            "lng": -82.4572,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Columbus Sheet & Fabric Cut",
            "description": "Industrial fabric laser cutting, thin sheet metal cutting, and complex gasket manufacturing.",
            "address": "400 High St, Columbus, OH",
            "capabilities": ["Laser Cutting"],
            "materials": ["Acrylic", "Leather", "Steel"],
            "hourly_rate": 52.0,
            "min_order": 150.0,
            "turnaround_days": 4,
            "rating": 4.4,
            "lat": 39.9612,
            "lng": -82.9988,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Salt Lake Laser Engineering",
            "description": "High-accuracy structural laser cutting for precision brackets, structural ply, and custom templates.",
            "address": "890 Depot Dr, Salt Lake City, UT",
            "capabilities": ["Laser Cutting"],
            "materials": ["Steel", "Wood", "Acrylic"],
            "hourly_rate": 58.0,
            "min_order": 100.0,
            "turnaround_days": 2,
            "rating": 4.7,
            "lat": 40.7608,
            "lng": -111.8910,
            "verified": True,
            "is_active": True
        },

        # --- Injection Molding (6 shops) ---
        {
            "name": "Irvine High-Volume Molding",
            "description": "State-of-the-art high-capacity plastic injection molding. Production runs from 5,000 to 1,000,000+ units.",
            "address": "1500 Technology Dr, Irvine, CA",
            "capabilities": ["Injection Molding"],
            "materials": ["ABS", "Polycarbonate", "Nylon"],
            "hourly_rate": 95.0,
            "min_order": 5000.0,
            "turnaround_days": 30,
            "rating": 4.9,
            "lat": 33.6846,
            "lng": -117.8265,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Houston Precision Plastics",
            "description": "Custom thermoplastic injection molding. Medical and oil field grade specialized materials.",
            "address": "440 industrial Rd, Houston, TX",
            "capabilities": ["Injection Molding"],
            "materials": ["ABS", "Polycarbonate", "Nylon", "PETG"],
            "hourly_rate": 88.0,
            "min_order": 3000.0,
            "turnaround_days": 25,
            "rating": 4.7,
            "lat": 29.7604,
            "lng": -95.3698,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Minneapolis Thermoplastics",
            "description": "Rapid tooling inserts and short-run injection molding (100 to 5,000 parts) using aluminum molds.",
            "address": "800 Industrial Blvd, Minneapolis, MN",
            "capabilities": ["Injection Molding"],
            "materials": ["ABS", "PLA", "Nylon"],
            "hourly_rate": 78.0,
            "min_order": 1500.0,
            "turnaround_days": 18,
            "rating": 4.6,
            "lat": 44.9778,
            "lng": -93.2650,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Silicon Valley Rapid Tooling",
            "description": "Ultra-fast prototyping molds, medical validation batches, and electronic casing molding.",
            "address": "900 Great America Pkwy, Santa Clara, CA",
            "capabilities": ["Injection Molding"],
            "materials": ["Polycarbonate", "ABS", "Nylon"],
            "hourly_rate": 110.0,
            "min_order": 4500.0,
            "turnaround_days": 20,
            "rating": 4.9,
            "lat": 37.3541,
            "lng": -121.9552,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Ohio Valley Mold & Die",
            "description": "Heavy industrial steel molds, automotive interior plastics, and durable hardware molding.",
            "address": "120 Foundry Lane, Canton, OH",
            "capabilities": ["Injection Molding"],
            "materials": ["ABS", "Polycarbonate", "Nylon"],
            "hourly_rate": 72.0,
            "min_order": 2000.0,
            "turnaround_days": 28,
            "rating": 4.3,
            "lat": 40.7989,
            "lng": -81.3784,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Charlotte Polymers Group",
            "description": "Specialized plastic components, custom consumer product packaging, and high-speed multi-cavity tooling.",
            "address": "330 Westinghouse Blvd, Charlotte, NC",
            "capabilities": ["Injection Molding"],
            "materials": ["ABS", "Polycarbonate", "Nylon", "PETG"],
            "hourly_rate": 82.0,
            "min_order": 2500.0,
            "turnaround_days": 22,
            "rating": 4.6,
            "lat": 35.2271,
            "lng": -80.8431,
            "verified": True,
            "is_active": True
        },

        # --- Sheet Metal & Welding (6 shops) ---
        {
            "name": "Seattle Heavy Weld & Metal",
            "description": "Structural steel sheet processing, structural beam welding, and heavy brackets.",
            "address": "440 Marginal Way, Seattle, WA",
            "capabilities": ["Sheet Metal", "Welding"],
            "materials": ["Steel", "Stainless Steel", "Aluminum"],
            "hourly_rate": 95.0,
            "min_order": 400.0,
            "turnaround_days": 10,
            "rating": 4.8,
            "lat": 47.6062,
            "lng": -122.3321,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Pasadena Sheet Metal Crafts",
            "description": "Precision electronic chassis, custom brackets, sheet metal punching and forming.",
            "address": "500 N Hill Ave, Pasadena, CA",
            "capabilities": ["Sheet Metal"],
            "materials": ["Aluminum", "Steel", "Stainless Steel"],
            "hourly_rate": 80.0,
            "min_order": 200.0,
            "turnaround_days": 6,
            "rating": 4.7,
            "lat": 34.1430,
            "lng": -118.1250,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Round Rock Structural Welding",
            "description": "Architectural steel elements, high-strength TIG/MIG welding, and industrial fabrications.",
            "address": "802 Industrial Blvd, Round Rock, TX",
            "capabilities": ["Welding"],
            "materials": ["Steel", "Stainless Steel", "Aluminum"],
            "hourly_rate": 85.0,
            "min_order": 300.0,
            "turnaround_days": 8,
            "rating": 4.7,
            "lat": 30.5083,
            "lng": -97.6789,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Tacoma Marine Fabrication",
            "description": "Heavy marine grade welding, custom hardware, structural aluminum sheets, and custom hulls.",
            "address": "150 Harbor Blvd, Tacoma, WA",
            "capabilities": ["Sheet Metal", "Welding"],
            "materials": ["Aluminum", "Stainless Steel", "Steel"],
            "hourly_rate": 105.0,
            "min_order": 1200.0,
            "turnaround_days": 15,
            "rating": 4.9,
            "lat": 47.2529,
            "lng": -122.4443,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Cleveland Custom Welders",
            "description": "Automotive assembly welding, robotic precision welds, and high-strength frame fabrication.",
            "address": "220 Euclid Ave, Cleveland, OH",
            "capabilities": ["Welding"],
            "materials": ["Steel", "Stainless Steel"],
            "hourly_rate": 78.0,
            "min_order": 250.0,
            "turnaround_days": 5,
            "rating": 4.5,
            "lat": 41.4993,
            "lng": -81.6944,
            "verified": False,
            "is_active": True
        },
        {
            "name": "Denver Sheet Metal Fabricators",
            "description": "High-speed CNC bending, turret punching, structural steel brackets, and sheet metal covers.",
            "address": "3300 Broadway, Denver, CO",
            "capabilities": ["Sheet Metal", "Laser Cutting"],
            "materials": ["Aluminum", "Steel", "Stainless Steel"],
            "hourly_rate": 88.0,
            "min_order": 350.0,
            "turnaround_days": 7,
            "rating": 4.7,
            "lat": 39.7392,
            "lng": -104.9903,
            "verified": True,
            "is_active": True
        },

        # --- Multidisciplinary (5 shops) ---
        {
            "name": "Vanguard Precision Industries",
            "description": "Complete manufacturing hub: high-end CNC milling, welding, structural sheet metal, and fast FDM prototypes.",
            "address": "900 Industrial Dr, Plano, TX",
            "capabilities": ["CNC Milling", "Sheet Metal", "Welding", "3D Printing (FDM)"],
            "materials": ["Steel", "Stainless Steel", "Aluminum", "Titanium", "PLA", "ABS"],
            "hourly_rate": 118.0,
            "min_order": 500.0,
            "turnaround_days": 8,
            "rating": 4.8,
            "lat": 33.0198,
            "lng": -96.6989,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Austin Manufacturing Nexus",
            "description": "Full lifecycle engineering and prototyping: CNC machining, fine laser cutting, rapid FDM and SLA prints.",
            "address": "810 Technology Blvd, Austin, TX",
            "capabilities": ["CNC Milling", "Laser Cutting", "3D Printing (FDM)", "3D Printing (SLA)"],
            "materials": ["Aluminum", "Brass", "PLA", "Resin", "Acrylic", "Wood"],
            "hourly_rate": 125.0,
            "min_order": 300.0,
            "turnaround_days": 4,
            "rating": 4.9,
            "lat": 30.2672,
            "lng": -97.7431,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Oak Ridge Advanced Materials",
            "description": "Extreme environment components: CNC milling, high-strength welding, titanium SLA 3D printing.",
            "address": "1 Advanced Way, Oak Ridge, TN",
            "capabilities": ["CNC Milling", "Welding", "3D Printing (SLA)"],
            "materials": ["Titanium", "Stainless Steel", "Resin"],
            "hourly_rate": 180.0,
            "min_order": 3000.0,
            "turnaround_days": 21,
            "rating": 5.0,
            "lat": 36.0104,
            "lng": -84.2696,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Detroit Prototype & Fabrication",
            "description": "Automotive Tier 1 design validation hub. Full metal structural fabrication, welding, and high-temp ABS SLA masters.",
            "address": "400 Grand Blvd, Detroit, MI",
            "capabilities": ["Sheet Metal", "Welding", "CNC Milling", "3D Printing (SLA)"],
            "materials": ["Steel", "Stainless Steel", "Aluminum", "Resin"],
            "hourly_rate": 115.0,
            "min_order": 1000.0,
            "turnaround_days": 9,
            "rating": 4.7,
            "lat": 42.3314,
            "lng": -83.0458,
            "verified": True,
            "is_active": True
        },
        {
            "name": "Pasadena Rapid Fab",
            "description": "Fast-turn custom metal brackets and FDM/SLA visual mockups for local technology companies.",
            "address": "200 Pasadena Ave, Pasadena, CA",
            "capabilities": ["Sheet Metal", "3D Printing (FDM)", "3D Printing (SLA)"],
            "materials": ["Aluminum", "Steel", "PLA", "ABS", "Resin"],
            "hourly_rate": 85.0,
            "min_order": 150.0,
            "turnaround_days": 3,
            "rating": 4.6,
            "lat": 34.1430,
            "lng": -118.1250,
            "verified": False,
            "is_active": True
        }
    ]

    print(f"Seeding {len(extra_shops)} extra manufacturing shops...")
    seeded_count = 0
    for shop in extra_shops:
        try:
            # Check if shop already exists
            existing = supabase.table("shops").select("id").eq("name", shop["name"]).execute()
            if existing.data:
                continue
                
            res = supabase.table("shops").insert(shop).execute()
            seeded_count += 1
        except Exception as e:
            print(f"Failed to insert {shop['name']}: {e}")
            
    print(f"Successfully seeded {seeded_count} new shops.")

if __name__ == "__main__":
    seed_large_shops()
